name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a crash, please ensure that you are on the latest version.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What behaviour did you expect to observe?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: fabric-version
    attributes:
      label: Fabric Version
      description: Which version of Fabric are you using?
    validations:
      required: false
  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: What version of Simple Shulker Preview are you are using?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Please paste any relevant log outputs here (without backtick formatting).
      render: shell
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Additional Context
      description: Please add any other important information here.
    validations:
      required: false